### ISSUE TITLE
Security and randomness of the nonce ("Lattice Attacks against Weak ECDSA Signatures")

### ISSUE THREAD

**Issue by miracle2k** [warner/python-ecdsa#103]
I am using this library as part of `ripple-python`. Recently, this paper was released, suggesting possible vulnerabilities if the nonce is not sufficiently random: https://eprint.iacr.org/2019/023.pdf

I am calling `sign_number` without giving a nonce myself (https://github.com/miracle2k/ripple-python/blob/master/ripple/sign.py#L118), which makes the library then use `randrange()` internally to compute `k`.

I suppose I should switch to deterministic signatures, as implemented in #10. However, can be assume that `randrange()` is sufficiently secure to generate a nonce?

**Comment by tomato42** [comment]
`randrange()` by default is using `os.urandom`, that's as best randomness as you can get:
https://github.com/warner/python-ecdsa/blob/795b8611b30fdf3a0d9f4717177bcc293b7eb092/src/ecdsa/util.py#L45-L55

Though please remember that the code is very vulnerable to side-channel attacks. Both because it uses naïve implementation of point multiplication and because [it is written in python](https://securitypitfalls.wordpress.com/2018/08/03/constant-time-compare-in-python/).
