### ISSUE TITLE
Importing anything from ecdsa is too expensive

### ISSUE THREAD

**Issue by jhance** [warner/python-ecdsa#180]
Since all the curves are constructed at import time in the modules __init__ using anything from ecdsa has a substantial import cost (like 0.3-0.4s which is pretty substantial). Computation at import time should be avoided.

**Comment by tomato42** [comment]
> Computation at import time should be avoided.

why? this way the cost is incurred once per application start

**Comment by jgphilpott** [comment]
I think I can see the case for avoiding computation at import... maybe I want to import ecdsa but not use any of its features until some event in the future triggered by human input. Doing the computation at the time of the event rather than at import could save time at application start. Personally I don't feel like 0.3-0.4s is a big deal but I guess it depends how time sensitive your application is.. is that what you're getting at @jhance ?

**Comment by tomato42** [comment]
the calculation that causes this is most likely the one that precomputes the multiplication table for curve generators, here:
https://github.com/warner/python-ecdsa/blob/93b04ba3ddb7c2716e07761393a179c061718c34/src/ecdsa/ellipticcurve.py#L163-L174

triggered by passing in `generator=True` here, and in the rest of that module:
https://github.com/warner/python-ecdsa/blob/93b04ba3ddb7c2716e07761393a179c061718c34/src/ecdsa/ecdsa.py#L296-L297

now, while it could be possible to compute that multiplication table once, and pass in as parameter to init instead of computing it, it would also force us to keep using this simplest possible precomputation table – something I'd rather not do (it's also the reason why `__precompute` is private)

the clever thing to do would be to generate those multiplication tables the first time the generator is actually used, but that is not inherently thread-safe (or easy to make thread-safe given our API)

finally, as far as performance goes, on my machine, import takes about 131ms:
```python
>>> a = time.time(); import ecdsa; b = time.time()
>>> b - a
0.13128066062927246
```
with the old 0.13 version a single keygen operation with smallest curve takes 30ms:
```
 NIST192p: siglen= 48, keygen=0.030s, sign=0.011s, verify=0.022s
 NIST224p: siglen= 56, keygen=0.041s, sign=0.015s, verify=0.030s
 NIST256p: siglen= 64, keygen=0.055s, sign=0.020s, verify=0.040s
SECP256k1: siglen= 64, keygen=0.055s, sign=0.020s, verify=0.039s
 NIST384p: siglen= 96, keygen=0.126s, sign=0.047s, verify=0.093s
 NIST521p: siglen=132, keygen=0.245s, sign=0.090s, verify=0.177s
```
at the same time, the "slow"-to-import 0.15 takes 0.3ms to keygen with the same curve...
that looks like a good trade for me

**Comment by oberstet** [comment]
> finally, as far as performance goes, on my machine, import takes about 131ms:

that's ~5x faster than in my testing on pypy3 / core i7 @2.6ghz:

```
(pypy37_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python
Python 3.7.4 (87875bf2dfd8, Sep 24 2020, 07:26:36)
[PyPy 7.3.2-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import timeit
>>>> def test():
....     from ecdsa.curves import SECP256k1
....     
>>>> timeit.timeit(test)
0.9488008650005213
>>>> timeit.timeit(test)
0.5613019509983133
>>>> timeit.timeit(test)
0.5426058019947959
>>>> timeit.timeit(test)
0.557845229996019
>>>> timeit.timeit(test)
0.5339794980027364
>>>> timeit.timeit(test)
0.5349632989964448
>>>> timeit.timeit(test)
0.5227033310002298
>>>> timeit.timeit(test)
0.5447136270013289
>>>> timeit.timeit(test)
0.5456890780042158
>>>> timeit.timeit(test)
0.5307007540031918
>>>> timeit.timeit(test)
0.5281276170062483
>>>> timeit.timeit(test)
0.5195286140005919
>>>> timeit.timeit(test)
0.5217169989991817
>>>> timeit.timeit(test)
0.5296866339995177
>>>> timeit.timeit(test)
0.5326904710018425
>>>> timeit.timeit(test)
0.5398623389992281
>>>> timeit.timeit(test)
0.5343465160040068
>>>> timeit.timeit(test)
0.5366757400042843
>>>> timeit.timeit(test)
0.5250207549979677
>>>> timeit.timeit(test)
0.5257596930023283
>>>> timeit.timeit(test)
0.5260231080028461
>>>> timeit.timeit(test)
0.5395378579996759
```

on cpy3 / raspberry pi3, above is ~30s (first call). 

this is quite excessive, and we will need to disable or remove it for our use. I'm wondering: what exactly is computed here and why?

**Comment by tomato42** [comment]
> > finally, as far as performance goes, on my machine, import takes about 131ms:
> 
> that's ~5x faster than in my testing on pypy3 / core i7 @2.6ghz:
> 
> ```
> (pypy37_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python
> Python 3.7.4 (87875bf2dfd8, Sep 24 2020, 07:26:36)
> [PyPy 7.3.2-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>>> import timeit
> >>>> def test():
> ....     from ecdsa.curves import SECP256k1
> ....     
> >>>> timeit.timeit(test)
> 0.9488008650005213
> >>>> timeit.timeit(test)
> 0.5613019509983133
> >>>> timeit.timeit(test)
> 0.5426058019947959
> >>>> timeit.timeit(test)
> 0.557845229996019
> >>>> timeit.timeit(test)
> 0.5339794980027364
> >>>> timeit.timeit(test)
> 0.5349632989964448
> >>>> timeit.timeit(test)
> 0.5227033310002298
> >>>> timeit.timeit(test)
> 0.5447136270013289
> >>>> timeit.timeit(test)
> 0.5456890780042158
> >>>> timeit.timeit(test)
> 0.5307007540031918
> >>>> timeit.timeit(test)
> 0.5281276170062483
> >>>> timeit.timeit(test)
> 0.5195286140005919
> >>>> timeit.timeit(test)
> 0.5217169989991817
> >>>> timeit.timeit(test)
> 0.5296866339995177
> >>>> timeit.timeit(test)
> 0.5326904710018425
> >>>> timeit.timeit(test)
> 0.5398623389992281
> >>>> timeit.timeit(test)
> 0.5343465160040068
> >>>> timeit.timeit(test)
> 0.5366757400042843
> >>>> timeit.timeit(test)
> 0.5250207549979677
> >>>> timeit.timeit(test)
> 0.5257596930023283
> >>>> timeit.timeit(test)
> 0.5260231080028461
> >>>> timeit.timeit(test)
> 0.5395378579996759
> ```
> 
> on cpy3 / raspberry pi3, above is ~30s (first call).

and what's the performance of signing or key gen? see my performance metrics in the README file
 
> this is quite excessive, and we will need to disable or remove it for our use. 

first: https://github.com/warner/python-ecdsa#security
second: if that's a problem for you, go and fix it; if you propose a PR that implements the "clever thing" then I'll review it and merge it if it's good enough
third: why are you "threatening" the stop using this project?

> I'm wondering: what exactly is computed here and why?

the table of generator point doublings and it's done so that scalar multiplications that use the generator point are much faster

**Comment by oberstet** [comment]
sorry, what I meant was disable the respective feature (or change it), not stop using python-ecdsa. 

> Do not allow attackers to measure how long it takes you to generate a keypair or sign a message. 

absolutely, there should be protection against side channel attacks, for these 2 actions, agreed.

what I am wondering about is why importing the library would generate a new key or sign a message.

"clever idea": not sure .. it seems the current protection against timing based side channel attacks is making every call to generate new key / sign message take the same run-time, eg by "busy waiting". is this the case? or does the "excessive" run-time result from actual computationally intensive calculation?

**Comment by oberstet** [comment]
> the table of generator point doublings and it's done so that scalar multiplications that use the generator point are much faster

another idea: would it make sense to do this pre-computation of generator points on a background thread (and only use the library once that comes back)?

**Comment by tomato42** [comment]
> sorry, what I meant was disable the respective feature (or change it), not stop using python-ecdsa.
> 
> > Do not allow attackers to measure how long it takes you to generate a keypair or sign a message.
> 
> absolutely, there should be protection against side channel attacks, for these 2 actions, agreed.

no, you misread it: python-ecdsa is not secure against side-channel attacks, not now, not ever, it's impossible to make it secure against side-channel attacks as long as it's written in pure python

if you need security against side-channel attacks: **do not use python-ecdsa**
 
> what I am wondering about is why importing the library would generate a new key or sign a message.
> 
> "clever idea": not sure .. it seems the current protection against timing based side channel attacks is making every call to generate new key / sign message take the same run-time, eg by "busy waiting". is this the case? or does the "excessive" run-time result from actual computationally intensive calculation?

it takes a long time to import because of code to make it faster, not to make it secure
no, busy waiting won't make it side-channel secure, nor will adding random noise to the time it takes to perform private key operations, see the Amazon's s2n Bleichenbacher workaround as a recent example

the only way to write side-channel secure code is to write code without secret data dependence

> > the table of generator point doublings and it's done so that scalar multiplications that use the generator point are much faster
> 
> another idea: would it make sense to do this pre-computation of generator points on a background thread (and only use the library once that comes back)?

yes, but that too requires playing around with locks/semaphores and if you do that, you may as well limit it to curves actually used

**Comment by oberstet** [comment]
> second: if that's a problem for you, go and fix it; if you propose a PR that implements the "clever thing" then I'll review it and merge it if it's good enough

done: here is my attempt https://github.com/warner/python-ecdsa/pull/212

**Comment by oberstet** [comment]
> not now, not ever, it's impossible to make it secure against side-channel attacks as long as it's written in pure python

my view: I don't see how it makes sense to talk about abstract programming languages and side-channel attack surface without putting that in context of a concrete language implementation and the attack scenario. but in any case, I'm interested in improving the library with secure and practical changes ..

> it takes a long time to import because of code to make it faster, not to make it secure

sure! however: why do I have to pay for precomputing multiplication tables for curves I'm not using at all? why does it precompute at import, rather than on first use?

> yes, but that too requires playing around with locks/semaphores ..

IMO depends: we use multiple threads, but objects are (almost) always owned and used from only 1 thread (by app design). so we wouldn't need locks, which are only needed once multiple different thread could read or write the same ecdsa object.

so again: why pay for stuff I don't use or need? sure: I should come up with PRs rather than complaining;) which I have for the current issue in above. for the threads thing: it is not currently a problem practically for us. but I will keep that in mind, since obviously deadlocks are always a risk with locks.

**Comment by tomato42** [comment]
> > not now, not ever, it's impossible to make it secure against side-channel attacks as long as it's written in pure python
> 
> my view: I don't see how it makes sense to talk about abstract programming languages and side-channel attack surface without putting that in context of a concrete language implementation and the attack scenario. but in any case, I'm interested in improving the library with secure and practical changes ..

the problem is not that Python is an interpreted high-level language, the problem is that the Python's `int()` objects, or `gmpy`'s `mpz()` objects, don't operate in constant time with respect to the Hamming weight or bit length of the values—and you can't build a side-channel free implementation if the building blocks you have access to aren't side-channel free

your time will be better spent migrating to a library that does provide Python bindings to implementations that are side-channel free, like pyca/cryptography—don't under-estimate the complexity of writing side-channel free code

> > it takes a long time to import because of code to make it faster, not to make it secure
> 
> sure! however: why do I have to pay for precomputing multiplication tables for curves I'm not using at all? why does it precompute at import, rather than on first use?

see my comments above—because it's complex and not an issue for my use cases so I didn't have an incentive to fix it

> > yes, but that too requires playing around with locks/semaphores ..
> 
> IMO depends: we use multiple threads, but objects are (almost) always owned and used from only 1 thread (by app design). so we wouldn't need locks, which are only needed once multiple different thread could read or write the same ecdsa object.

the problem is that the precomputation table is associated with the generator point of curve, and that object is shared between the threads as long as different threads use ecdsa

second, even if your usage limits use of ecdsa to single thread it's only your use case, the library now is thread-safe, so I'd rather keep it like that
 
> so again: why pay for stuff I don't use or need? sure: I should come up with PRs rather than complaining;) which I have for the current issue in above. for the threads thing: it is not currently a problem practically for us. but I will keep that in mind, since obviously deadlocks are always a risk with locks.

**Comment by oberstet** [comment]
> the problem is that the Python's int() objects, or gmpy's mpz() objects, don't operate in constant time with respect to the Hamming weight or bit length of the values

ok, makes sense. if the run-time of integer ops done on the range of integers used in the lib depends on the integer values, the run-times leak info.

fwiw, what I meant: even so ^, these are details of a specific implementation (such as cpython), not specified in the python language itself (I _think_). I would also think that having constant time integer atomic operations is only a sufficient condition to not leak information. not having any systematic or statistical dependence between integer op run-time and the actual integers being process is probably necessary.

>  that object is shared between the threads as long as different threads use ecdsa

what object? are there global objects within the library itself that are being shared?

----

I am interested in a) avoiding expensive computation for stuff I don't need altogether and b) postpone computation for stuff I use until it is needed (that is, when I first use it)

rgd locks: there is a price to pay. it would be easy to make it so a user can_optionally_ turn it off and save the associated costs and deadlock risks. eg by having the RWLock implementation in 2 flavors with 1 being zero-op. would that be sth be considered for merging?

**Comment by tomato42** [comment]
> > the problem is that the Python's int() objects, or gmpy's mpz() objects, don't operate in constant time with respect to the Hamming weight or bit length of the values
> 
> ok, makes sense. if the run-time of integer ops done on the range of integers used in the lib depends on the integer values, the run-times leak info.
> 
> fwiw, what I meant: even so ^, these are details of a specific implementation (such as cpython), not specified in the python language itself (I _think_).

yes, it's not inherent to the language, the problem is that doing arbitrary precision arithmetic in side-channel free manner is really hard, it's not something you get accidentally; it would require very specialised API for the operations on the integers and then very careful use of that API (see the low level API in gmplib for a taste)

> I would also think that having constant time integer atomic operations is only a sufficient condition to not leak information. not having any systematic or statistical dependence between integer op run-time and the actual integers being process is probably necessary.

no, it's a prerequisite, but it's not sufficient; the way you operate on those integers needs to preserve that data-independence; and the algorithms that are implemented in python-ecdsa do not even attempt that (as it requires branch-less programming, and that's not possible if even xor is data dependent)
 
> > that object is shared between the threads as long as different threads use ecdsa
> 
> what object? are there global objects within the library itself that are being shared?

all the `curve` and `generator` objects defined in ecdsa/ecsda:
`curve_256`, `generator_256`, ...
https://github.com/warner/python-ecdsa/blob/f27b20ff2a67c6b1afe473dd347c8da5c4017e34/src/ecdsa/ecdsa.py#L419-L422

---
 
> I am interested in a) avoiding expensive computation for stuff I don't need altogether and b) postpone computation for stuff I use until it is needed (that is, when I first use it)

fine by me
 
> rgd locks: there is a price to pay. it would be easy to make it so a user can_optionally_ turn it off and save the associated costs and deadlock risks. eg by having the RWLock implementation in 2 flavors with 1 being zero-op. would that be sth be considered for merging?

maybe...? is it really expensive compared to all the operations that would use them? we only need to fire that lock when we perform scalar multiplication, that is, _the_ most expensive operation you can do in python-ecdsa...
