### ISSUE TITLE
Please do not bundle `six`

### ISSUE THREAD

**Issue by htgoebel** [warner/python-ecdsa#59]
Is there any reason to bundle the `six` module? If it is only convenience for the user please remove it and add an `install_requires=['six']` to setup.py.

Bundling 3rd packages leads to duplicate code in a system and may lead to maintenance problems. And in your case not doing this saves you the work of updating the packages regularly :-)

**Comment by sylvainpelissier** [comment]
Should be fixed in #60 .

**Comment by warner** [comment]
Yeah, I wanted to avoid having any dependencies. `python-ecdsa` currently requires nothing outside of the python standard library. At the time, I'd had a lot of bad experiences with dependencies.

Since then, though, `pip` has gotten a lot better, so I think I'm ok with unbundling `six` now. I'll take a look at the PR. Thanks!
